"""initial schema

Revision ID: f5dd5cfaf313
Revises: 
Create Date: 2026-05-17 21:35:47.385221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5dd5cfaf313'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="ID unique de l'utilisateur"),
    sa.Column('email', sa.String(length=255), nullable=False, comment="Email de l'utilisateur (unique)"),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Mot de passe hashé (bcrypt)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="Nom complet de l'utilisateur"),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment="Nom de l'entreprise"),
    sa.Column('role_arn', sa.String(length=255), nullable=True, comment='Role ARN AWS pour les scans (optionnel)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création du compte'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Date de dernière connexion'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Compte actif ou désactivé'),
    sa.Column('reset_token', sa.String(length=255), nullable=True, comment='Token pour réinitialisation du mot de passe'),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True, comment="Date d'expiration du token de réinitialisation"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_resources', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_session_id'), 'scan_runs', ['session_id'], unique=False)
    op.create_table('ec2_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('instance_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('instance_type', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('ami_id', sa.String(length=50), nullable=True),
    sa.Column('availability_zone', sa.String(length=50), nullable=True),
    sa.Column('tenancy', sa.String(length=20), nullable=True),
    sa.Column('architecture', sa.String(length=20), nullable=True),
    sa.Column('virtualization_type', sa.String(length=20), nullable=True),
    sa.Column('vpc_id', sa.String(length=50), nullable=True),
    sa.Column('subnet_id', sa.String(length=50), nullable=True),
    sa.Column('private_ip', sa.String(length=15), nullable=True),
    sa.Column('public_ip', sa.String(length=15), nullable=True),
    sa.Column('iam_profile', sa.String(length=255), nullable=True),
    sa.Column('root_device_name', sa.String(length=50), nullable=True),
    sa.Column('launch_time', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('ebs_volumes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ec2_instances_client_id'), 'ec2_instances', ['client_id'], unique=False)
    op.create_index(op.f('ix_ec2_instances_instance_id'), 'ec2_instances', ['instance_id'], unique=False)
    op.create_index(op.f('ix_ec2_instances_region'), 'ec2_instances', ['region'], unique=False)
    op.create_index(op.f('ix_ec2_instances_state'), 'ec2_instances', ['state'], unique=False)
    op.create_table('s3_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=True),
    sa.Column('versioning_enabled', sa.Boolean(), nullable=True),
    sa.Column('public_access_blocked', sa.Boolean(), nullable=True),
    sa.Column('public_read_enabled', sa.Boolean(), nullable=True),
    sa.Column('bucket_policy_enabled', sa.Boolean(), nullable=True),
    sa.Column('lifecycle_enabled', sa.Boolean(), nullable=True),
    sa.Column('cors_enabled', sa.Boolean(), nullable=True),
    sa.Column('website_enabled', sa.Boolean(), nullable=True),
    sa.Column('logging_enabled', sa.Boolean(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('replication_enabled', sa.Boolean(), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s3_buckets_bucket_name'), 's3_buckets', ['bucket_name'], unique=False)
    op.create_index(op.f('ix_s3_buckets_client_id'), 's3_buckets', ['client_id'], unique=False)
    op.create_index(op.f('ix_s3_buckets_region'), 's3_buckets', ['region'], unique=False)
    op.create_table('ec2_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ec2_instance_id', sa.Integer(), nullable=False),
    sa.Column('cpu_utilization_avg', sa.Float(), nullable=True),
    sa.Column('memory_utilization_avg', sa.Float(), nullable=True),
    sa.Column('network_in_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_out_bytes', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ec2_instance_id'], ['ec2_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s3_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s3_bucket_id', sa.Integer(), nullable=False),
    sa.Column('all_requests', sa.BigInteger(), nullable=True),
    sa.Column('get_requests', sa.BigInteger(), nullable=True),
    sa.Column('put_requests', sa.BigInteger(), nullable=True),
    sa.Column('delete_requests', sa.BigInteger(), nullable=True),
    sa.Column('errors_4xx', sa.BigInteger(), nullable=True),
    sa.Column('errors_5xx', sa.BigInteger(), nullable=True),
    sa.Column('first_byte_latency_avg', sa.Float(), nullable=True),
    sa.Column('total_request_latency_avg', sa.Float(), nullable=True),
    sa.Column('bytes_downloaded', sa.BigInteger(), nullable=True),
    sa.Column('bytes_uploaded', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['s3_bucket_id'], ['s3_buckets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3_performance')
    op.drop_table('ec2_performance')
    op.drop_index(op.f('ix_s3_buckets_region'), table_name='s3_buckets')
    op.drop_index(op.f('ix_s3_buckets_client_id'), table_name='s3_buckets')
    op.drop_index(op.f('ix_s3_buckets_bucket_name'), table_name='s3_buckets')
    op.drop_table('s3_buckets')
    op.drop_index(op.f('ix_ec2_instances_state'), table_name='ec2_instances')
    op.drop_index(op.f('ix_ec2_instances_region'), table_name='ec2_instances')
    op.drop_index(op.f('ix_ec2_instances_instance_id'), table_name='ec2_instances')
    op.drop_index(op.f('ix_ec2_instances_client_id'), table_name='ec2_instances')
    op.drop_table('ec2_instances')
    op.drop_index(op.f('ix_scan_runs_session_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

